# Generated by Django 4.1.7 on 2023-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_usercus_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercus',
            name='birthday',
            field=models.DateField(default='1111/01/01'),
        ),
    ]
