# Generated by Django 4.1.7 on 2023-06-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_usercus_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d'),
        ),
    ]
