# Generated by Django 4.1.7 on 2023-06-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_usercus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercus',
            name='birthday',
        ),
    ]
