# Generated by Django 4.1.7 on 2023-07-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_alter_usercus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercus',
            name='group',
            field=models.CharField(blank=True, choices=[('regular', 'regular'), ('moderator', 'moderator'), ('publisher', 'publisher')], default='regular', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercus',
            name='mail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercus',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercus',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
